INSERT INTO users(login, display_name, year_of_birth)VALUES
('kasia85', 'Kasia Nowak', 1985),
('piotr_90', 'Piotr Kowalski', 1990),
('ania1980', 'Ania Wiśniewska', 1980),
('tomek95', 'Tomek Wójcik', 1995),
('magda2000', 'Magda Kowalczyk', 2000),
('jakub87', 'Jakub Woźniak', 1987),
('ewa75', 'Ewa Dąbrowska', 1975),
('michal92', 'Michał Lewandowski', 1992),
('ola83', 'Ola Kamińska', 1983),
('maciek78', 'Maciek Zieliński', 1978),
('agnieszka86', 'Agnieszka Szymańska', 1986),
('marek98', 'Marek Woźniak', 1998),
('dorota72', 'Dorota Kozłowska', 1972),
('adam89', 'Adam Jankowski', 1989),
('monika79', 'Monika Mazur', 1979),
('bartek2001', 'Bartek Kwiatkowski', 2001),
('natalia91', 'Natalia Krawczyk', 1991),
('krzysztof82', 'Krzysztof Pawlak', 1982),
('patrycja94', 'Patrycja Grabowska', 1994),
('grzegorz74', 'Grzegorz Michalski', 1974);

INSERT INTO post(body, user_id) VALUES
('Zaczynam naukę Pythona - na razie super wrażenia!', 1),
('Moje przemyślenia na temat korzyści z TDD w programowaniu.', 2),
('Eksploracja świata uczenia maszynowego.', 2),
('Udało mi się uruchomić moją pierwszą aplikację webową w Node.js!', 3),
('Czy Rust to przyszłość programowania systemowego? Moje przemyślenia.', 2),
('Uczestniczyłem w moim pierwszym hackathonie i było niesamowicie!', 7),
('Java kontra Kotlin do programowania Android - które preferujecie?', 14),
('Jak być na bieżąco ze stale zmieniającym się krajobrazem technologicznym.', 1),
('Wyzwania pracy zdalnej w zespołach programistycznych.', 9),
('Dlaczego uważam, że programowanie funkcyjne ma znaczenie.', 13),
('Zanurzam się w data science: Moja dotychczasowa podróż.', 6),
('Zrozumienie Dockera i konteneryzacji: Przewodnik dla początkujących.', 18),
('Odkrywanie nowych funkcji w najnowszym wydaniu Angular.', 10),
('Porady dotyczące efektywnego projektowania i zarządzania bazami danych.', 17),
('Jaki jest wasz ulubiony IDE do programowania w Pythonie i dlaczego?', 4),
('Wzrost sztucznej inteligencji i jej implikacje dla przyszłych programistów.', 17),
('Tworzenie responsywnego UI za pomocą React Native: Moje doświadczenia.', 15),
('Znaczenie cyberbezpieczeństwa w programowaniu.', 13),
('Rozpoczęcie pracy z projektami open-source.', 20),
('Technologia blockchain: Nie tylko kryptowaluty.', 16),
('Próbuję zrozumieć algorytmy sortowania, jakieś wskazówki?', 2),
('Mój pierwszy projekt w Ruby on Rails!', 5),
('Opublikowałem moją pierwszą aplikację mobilną na Androida!', 10),
('Czy ktoś używał Fluttera? Jakie są wasze doświadczenia?', 3),
('Napisałem mojego pierwszego bota do Discorda, chcecie zobaczyć?', 7),
('Jakie biblioteki do UI polecacie w React?', 4),
('Przełom w uczeniu maszynowym - co myślicie o GPT-4?', 9),
('Szukam kursów do nauki Cloud Computing, jakieś sugestie?', 6),
('Czy warto uczyć się Go w 2023 roku?', 12),
('Jak zaimplementować mikroserwisy w Node.js?', 13),
('Porady dla początkujących w zakresie bezpieczeństwa cybernetycznego.', 10),
('Jak zarządzać stanem w dużych aplikacjach React?', 14),
('Budowanie interfejsów użytkownika za pomocą SwiftUI.', 13),
('Zaawansowane techniki w CSS, które każdy front-endowiec powinien znać.', 15),
('Czy testy jednostkowe naprawdę są takie ważne?', 18),
('Jakie frameworki JavaScript są najlepsze dla początkujących?', 16),
('Integracja CI/CD w projekcie open source - moje doświadczenia.', 17),
('Wprowadzenie do programowania funkcyjnego w JavaScript.', 17),
('Optymalizacja wydajności aplikacji webowych.', 1),
('Jakie są najlepsze praktyki w zarządzaniu bazami danych?', 20),
('Eksperymentuję z WebAssembly - niesamowite możliwości!', 4),
('Jakie są wasze ulubione narzędzia do debugowania JavaScript?', 3),
('Wyzwania związane z przetwarzaniem dużych zbiorów danych.', 5),
('Moje doświadczenia z migracją bazy danych - nauki i wskazówki.', 2),
('Automatyzacja testów UI - jakie narzędzia polecacie?', 7),
('Optymalizacja zapytań SQL - moje najlepsze praktyki.', 9),
('Czy warto się uczyć Angulara w 2023 roku?', 6),
('Jak utrzymać wysoką jakość kodu w dużym projekcie?', 10),
('Zarządzanie zależnościami w projektach Python.', 13),
('Jak zacząć z Machine Learning, będąc programistą webowym?', 10),
('Wskazówki dotyczące pisania czytelnego i utrzymywalnego kodu.', 12),
('Przełączam się z PHP na Node.js - oto moje obserwacje.', 15),
('Kiedy i dlaczego warto używać TypeScript w projektach JavaScript.', 14),
('Wdrażanie aplikacji na platformach chmurowych - AWS vs Azure.', 13),
('Zarządzanie pamięcią w aplikacjach C++.', 16),
('Sekrety efektywnej pracy w zespole programistycznym.', 17),
('Jak zbudować skalowalną architekturę mikroserwisów.', 18),
('Recenzja najnowszego kursu programowania w Pythonie.', 17),
('Jak radzić sobie z zablokowanymi procesami w aplikacjach wielowątkowych.', 1),
('Tworzenie aplikacji mobilnych z reaktywnymi interfejsami użytkownika.', 20),
('Porównanie Vue.js i React.js - moje osobiste doświadczenia.', 3),
('Jak efektywnie zarządzać stanem w aplikacjach Vue?', 2),
('Tworzenie interaktywnych wykresów z D3.js.', 5),
('Korzystanie z GraphQL w projektach na dużą skalę.', 7),
('Najlepsze praktyki dotyczące bezpieczeństwa API RESTful.', 6),
('Jak napisać wydajny i skalowalny backend w Express.js?', 4),
('Zalety i wady korzystania z Firebase w aplikacjach webowych.', 10),
('Automatyzacja pracy domowej z Pythonem - moje projekty.', 10),
('Poznawanie architektury systemów rozproszonych.', 1),
('Jak nauczyć się programowania w C# - porady dla początkujących.', 12),
('Eksploracja wzorców projektowych w OOP.', 14),
('Zagłębianie się w język programowania Swift.', 13),
('Budowa chatbota przy użyciu Node.js - od A do Z.', 9),
('Wprowadzenie do tworzenia gier w Unity - pierwsze kroki.', 13),
('Zarządzanie zespołem programistów - moje spostrzeżenia.', 15),
('Najlepsze środowiska programistyczne dla Pythona.', 16),
('Rozwój osobisty jako programista - jakie umiejętności są kluczowe?', 18),
('Implementacja wzorca MVC w aplikacjach JavaScript.', 17),
('Praca zdalna jako programista - jak efektywnie organizować czas?', 17),
('Testowanie komponentów React za pomocą Jest i Enzyme.', 20),
('Rozpoczynam projekt wykorzystujący mikrokontrolery Arduino - jakieś wskazówki?', 14),
('Zintegrowane środowisko programistyczne (IDE) a edytory kodu - moje przemyślenia.', 2),
('Przegląd narzędzi do zarządzania bazami danych SQL.', 4),
('Jakie są najlepsze praktyki w pisaniu skryptów Bash?', 6),
('Wykorzystanie AI do automatyzacji testów - przyszłość testowania oprogramowania.', 10),
('Zalety i wady używania Kubernetes w środowiskach produkcyjnych.', 10),
('Eksperymenty z Raspberry Pi - nieograniczone możliwości małego komputera.', 12),
('Jakie frameworki CSS warto znać w 2023 roku?', 1),
('Zarządzanie projektem programistycznym - Agile vs Waterfall.', 3),
('Wprowadzenie do analizy danych z Pandas w Pythonie.', 5),
('Jak zacząć karierę w cyberbezpieczeństwie - porady dla początkujących.', 7),
('Rozwój aplikacji klienckich z wykorzystaniem Electron.js.', 9),
('Zaawansowane techniki zarządzania stanem w React.', 13),
('Kiedy i dlaczego warto stosować wzorzec Singleton w Java.', 13),
('Dlaczego warto nauczyć się programowania w Rust.', 15),
('Jakie są wyzwania w pracy zdalnej dla programistów.', 17),
('Porady dotyczące efektywnego wykorzystania Git w pracy zespołowej.', 17),
('Zarządzanie zależnościami w projektach Ruby on Rails.', 16),
('Najlepsze narzędzia do monitorowania wydajności aplikacji webowych.', 18),
('Porównanie Fluttera i React Native dla rozwoju mobilnego.', 20);